name: Build and publish demos

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to upload artifacts to releases (and pushing the version update)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: acifani/setup-tinygo@v1
      - run: mkdir -p public

      - name: Build sdf-viewer-go/example
        run: |
          cd $GITHUB_WORKSPACE/sdf-viewer-go/example
          tinygo build -o ../../public/sdf-viewer-go.wasm -target wasi -opt 2 -x -no-debug -wasm-abi generic .

      - name: Build sdf-viewer-go-sdfx/example
        run: |
          cd $GITHUB_WORKSPACE/sdf-viewer-go-sdfx/example
          tinygo build -o ../../public/sdf-viewer-go-sdfx.wasm -target wasi -opt 2 -x -no-debug -wasm-abi generic .

      - name: Build sdf-viewer-go-sdf/example
        run: |
          cd $GITHUB_WORKSPACE/sdf-viewer-go-sdf/example
          tinygo build -o ../../public/sdf-viewer-go-sdf.wasm -target wasi -opt 2 -x -no-debug -wasm-abi generic .

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: public
